### ISSUE TITLE
Execcuting UBW_C.py for CIFAR10

### ISSUE THREAD

**Issue by Suhina123** [THUYimingLi/Untargeted_Backdoor_Watermark#3]
Dear authors,

I am trying to execute UBW_C.py as a part of my project. However, the execution time is very large. Please let me know if I am going wrong anywhere, I am using Google colabs and have also changed the runtime  type  to GPU.
![UBW_C](https://github.com/THUYimingLi/Untargeted_Backdoor_Watermark/assets/129325719/e1714a16-bc29-4b9b-8a24-1940df4c2027)

**Comment by THUYimingLi** [comment]
Hi, Suhina123,

Thanks for reaching out! In general, it may take a few hours to run UBW-C on CIFAR-10 since we need to train the model 200 epochs. I am unsure what your 'the execution time is very large' means. BTW, it seems that your codes generate some warnings. I would recommend that you first check the GPU memory usage when the code is running (via nvidia-smi or similar approaches) to ensure that your codes correctly use GPUs. If it still not works for you, you should try using a consistent Anaconda Environment to us via pip install -r requirements.txt (in the File Directory of UBW-P)

Best,
Yiming

**Comment by THUYimingLi** [comment]
> Dear authors,
> 
> I am trying to execute UBW_C.py as a part of my project. However, the execution time is very large. Please let me know if I am going wrong anywhere, I am using Google colabs and have also changed the runtime type to GPU. ![UBW_C](https://private-user-images.githubusercontent.com/129325719/291097365-e1714a16-bc29-4b9b-8a24-1940df4c2027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTgyNDEsIm5iZiI6MTcwMzIxNzk0MSwicGF0aCI6Ii8xMjkzMjU3MTkvMjkxMDk3MzY1LWUxNzE0YTE2LWJjMjktNGI5Yi04YTI0LTE5NDBkZjRjMjAyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwNDA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmNmMTFlNDczZTg0MzQ3ZmU4N2YzNmM5OTZlMzkxZTFjYzNiMTRmMzE1YWFhNTAyNjkwMDJiMjdkMDM4YmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wmi8A0oyrisSy1ngsvZRtJNgeQYR8wgZbY96oRI5RAA)

Hi, have you solved the runing problem? I will leave this issue open for a few days in case you still have some questions. I will close it after a week if there is no new response :)

**Comment by Suhina123** [comment]
Hello,

I was successfully able to execute UBW_C.py file!:) It is taking about 10 hours to complete 27 epochs. Could you please tell me how much time it should have taken? And also, if there is a way I can determine if the training has been complete after a few epochs so that I wouldn't have to wait for long. 

I am unable to understand the structure of UBW-P. Please let me know the scripts that have to be run to understand the part that has been explained in the research paper.

Thank you,
Suhina

**Comment by THUYimingLi** [comment]
> Hello,
> 
> I was successfully able to execute UBW_C.py file!:) It is taking about 10 hours to complete 27 epochs. Could you please tell me how much time it should have taken? And also, if there is a way I can determine if the training has been complete after a few epochs so that I wouldn't have to wait for long.
> 
> I am unable to understand the structure of UBW-P. Please let me know the scripts that have to be run to understand the part that has been explained in the research paper.
> 
> Thank you, Suhina

Hi, Suhina,

1. Unfortunately, similar to all methods based on bi-level optimization, UBW-C is really slow. You can run fewer epochs to reduce the time. Specifically, you can first find a suitable training schedule for standard training on CIFAR-10 and use the same one for UBW-C. 
2. You can simply run [train_UBW_P.py](https://github.com/THUYimingLi/Untargeted_Backdoor_Watermark/blob/main/UBW-P/train_UBW_P.py) for UBW-P. 

Best,
Yiming
