### ISSUE TITLE
UBW_C understanding

### ISSUE THREAD

**Issue by Suhina123** [THUYimingLi/Untargeted_Backdoor_Watermark#5]
Dear Authors,

I am a bit confused about the clean label setting, in the paper it has been mentioned that the clean label setting is worth further explanation. But the code has been implemented. Could you please briefly explain how the clean label attack works?

Best Regards,
Suhina

**Comment by THUYimingLi** [comment]
> Dear Authors,
> 
> I am a bit confused about the clean label setting, in the paper it has been mentioned that the clean label setting is worth further explanation. But the code has been implemented. Could you please briefly explain how the clean label attack works?
> 
> Best Regards, Suhina

Hi, Suhina,

Please find more technical details in the Section 3.4 and Appendix A-B of our paper.
